export const veiculos = [
  {
    id: "1",
    title: "Fusca",
    status: "Usado",
    price: 10000,
    image: "https://www.picellileiloes.com.br/arquivos/leiloes/lotes/imagens/063f20dcdabf1f.jpg",
    cambio: "Manual",
    year: 1970,
    description: "Fusca 1970, em bom estado de conservação, com alguns detalhes na pintura.",
    ports: '2 portas',
  },
  {
    id: "2",
    title: "Gol",
    status: "Usado",
    price: 15000,
    image: "https://www.picellileiloes.com.br/arquivos/leiloes/lotes/imagens/063f20dcdabf1f.jpg",
    cambio: "Manual",
    year: 1980,
    description: "Gol 1980, em bom estado de conservação, com alguns detalhes na pintura.",
    ports: '4 portas',
  },
  {
    id: "3",
    title: "Fiat Uno",
    status: "Usado",
    price: 20000,
    image: "https://www.picellileiloes.com.br/arquivos/leiloes/lotes/imagens/063f20dcdabf1f.jpg",
    cambio: "Manual",
    year: 1990,
    description: "Fiat Uno 1990, em bom estado de conservação, com alguns detalhes na pintura.",
    ports: '4 portas',
  },
  {
    id: "4",
    title: "Fiat Palio",
    status: "Usado",
    price: 25000,
    image: "https://www.picellileiloes.com.br/arquivos/leiloes/lotes/imagens/063f20dcdabf1f.jpg",
    cambio: "Manual",
    year: 2000,
    description: "Fiat Palio 2000, em bom estado de conservação, com alguns detalhes na pintura.",
    ports: '4 portas',
  },
  {
    id: "5",
    title: "Fiat Punto",
    status: "Usado",
    price: 30000,
    image: "https://www.picellileiloes.com.br/arquivos/leiloes/lotes/imagens/063f20dcdabf1f.jpg",
    cambio: "Manual",
    year: 2010,
    description: "Fiat Punto 2010, em bom estado de conservação, com alguns detalhes na pintura.",
    ports: '4 portas',
  },
  {
    id: "6",
    title: "Fiat Cronos",
    status: "Usado",
    price: 35000,
    image: "https://www.picellileiloes.com.br/arquivos/leiloes/lotes/imagens/063f20dcdabf1f.jpg",
    cambio: "Manual",
    year: 2020,
    description: "Fiat Cronos 2020, em bom estado de conservação, com alguns detalhes na pintura.",
    ports: '4 portas',
  },
  {
    id: "7",
    title: "marca 1",
    status: "Usado",
    price: 35000,
    image: "https://www.picellileiloes.com.br/arquivos/leiloes/lotes/imagens/063f20dcdabf1f.jpg",
    cambio: "Manual",
    year: 2020,
    description: "Fiat Cronos 2020, em bom estado de conservação, com alguns detalhes na pintura.",
    ports: '4 portas',
  }
]